# This is a basic workflow to help you get started with Actions

name: Common.Address.WF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.HERE_PLATFORM_API_KEY }}
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Test print of the API key
    - name: Use API key
      run: |
       echo Using API key: $API_KEY

    # Add API Key to appsettings.json when cloned, forked, or local repo sync
    - name: Inject API key into appsettings.json
      run: |
       jq --arg key "$API_KEY" '.Here.ApiKey = $key' ValidateAddress/Common.Address/appsettings.json > temp.json && mv temp.json ValidateAddress/Common.Address/appsettings.json
  # This workflow contains a single job called "build"
  # build:
    # The type of runner that the job will run on
   # runs-on: ubuntu-latest

    # Gets API KEY for HERE Platform
    # env:
      # API_KEY: ${{ secrets.HERE_PLATFORM_API_KEY }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: Checkout code
      # - uses: actions/checkout@v4

      # Test print of the API key
      # - name: Use API key
      # - run: |
          # echo Using API key: $API_KEY
      
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
